import {
  Airbnb,
  Alipay,
  Anthropic,
  Azure,
  Baichuan,
  Bedrock,
  Chrome,
  Claude,
  Cline,
  Cloudflare,
  Copilot,
  Coze,
  Cursor,
  DeepInfra,
  DeepSeek,
  Dify,
  Discord,
  Docker,
  Doubao,
  ElevenLabs,
  Figma,
  Firefox,
  Fireworks,
  Flowith,
  Gemini,
  Github,
  Grok,
  Groq,
  HuggingFace,
  Hunyuan,
  Hyperbolic,
  Instagram,
  Kling,
  Kubernetes,
  LangChain,
  Linear,
  LlamaIndex,
  Meta,
  Midjourney,
  Minimax,
  Mistral,
  Moonshot,
  N8n,
  Netflix,
  Notion,
  Novita,
  Nvidia,
  Ollama,
  OpenAI,
  OpenRouter,
  PayPal,
  Perplexity,
  PlayStation,
  Python,
  Qwen,
  React,
  Reddit,
  Replicate,
  Runway,
  SiliconCloud,
  Spotify,
  Steam,
  Stripe,
  Suno,
  Telegram,
  TikTok,
  Together,
  Uber,
  V0,
  Vercel,
  VertexAI,
  WeChat,
  WhatsApp,
  Windsurf,
  X,
  Xiaohongshu,
  YouTube,
  Zapier,
  Zhipu,
} from "@yldm-tech/ai-logo";

import { type CompoundIcon, entries, type IconEntry, preferred } from "../registry";

/**
 * The brands the landing page draws, imported by name.
 *
 * This is the one place in the app that names icons one by one, and it is deliberate twice over. It is what a real consumer writes — the gallery's `import * as` is the unusual case, not this — and it is what keeps the entry chunk to the 79 marks actually on screen (two AI tracks, one services track, and Anthropic for the lookup card) rather than the whole set. The order is the order they are met: the most recognisable first, so the first row of the marquee is the one a reader scans.
 */
const ICONS = {
  Airbnb,
  Alipay,
  Anthropic,
  Azure,
  Baichuan,
  Bedrock,
  Chrome,
  Claude,
  Cline,
  Cloudflare,
  Copilot,
  Coze,
  Cursor,
  DeepInfra,
  DeepSeek,
  Dify,
  Discord,
  Docker,
  Doubao,
  ElevenLabs,
  Figma,
  Firefox,
  Fireworks,
  Flowith,
  Gemini,
  Github,
  Grok,
  Groq,
  HuggingFace,
  Hunyuan,
  Hyperbolic,
  Instagram,
  Kling,
  Kubernetes,
  LangChain,
  Linear,
  LlamaIndex,
  Meta,
  Midjourney,
  Minimax,
  Mistral,
  Moonshot,
  N8n,
  Netflix,
  Notion,
  Novita,
  Nvidia,
  Ollama,
  OpenAI,
  OpenRouter,
  PayPal,
  Perplexity,
  PlayStation,
  Python,
  Qwen,
  React,
  Reddit,
  Replicate,
  Runway,
  SiliconCloud,
  Spotify,
  Steam,
  Stripe,
  Suno,
  Telegram,
  TikTok,
  Together,
  Uber,
  V0,
  Vercel,
  VertexAI,
  WeChat,
  WhatsApp,
  Windsurf,
  X,
  Xiaohongshu,
  YouTube,
  Zapier,
  Zhipu,
} as unknown as Record<string, CompoundIcon | undefined>;

const ORDER = [
  "OpenAI",
  "Claude",
  "Gemini",
  "Grok",
  "DeepSeek",
  "Qwen",
  "Mistral",
  "Meta",
  "Perplexity",
  "Cursor",
  "HuggingFace",
  "Ollama",
  "Copilot",
  "Midjourney",
  "Suno",
  "ElevenLabs",
  "Runway",
  "Kling",
  "Moonshot",
  "Zhipu",
  "Minimax",
  "Doubao",
  "Hunyuan",
  "Baichuan",
  "Groq",
  "Together",
  "Fireworks",
  "Replicate",
  "OpenRouter",
  "SiliconCloud",
  "Novita",
  "DeepInfra",
  "Hyperbolic",
  "Nvidia",
  "Azure",
  "Bedrock",
  "VertexAI",
  "Cloudflare",
  "Vercel",
  "Github",
  "Notion",
  "Figma",
  "Zapier",
  "LangChain",
  "LlamaIndex",
  "Dify",
  "Coze",
  "N8n",
  "Flowith",
  "Cline",
  "Windsurf",
  "V0",
];

/** The third marquee track: mainstream services beyond AI, in a row of their own so the first screen shows that the set is not only AI brands. */
const SERVICE_ORDER = [
  "YouTube",
  "Spotify",
  "Netflix",
  "X",
  "Instagram",
  "TikTok",
  "Discord",
  "WeChat",
  "Telegram",
  "WhatsApp",
  "Reddit",
  "Xiaohongshu",
  "Docker",
  "Kubernetes",
  "Python",
  "React",
  "Linear",
  "Stripe",
  "PayPal",
  "Alipay",
  "Airbnb",
  "Uber",
  "Steam",
  "PlayStation",
  "Chrome",
  "Firefox",
];

const byId = new Map(entries.map((entry) => [entry.id, entry]));

/** A name that is in the list but not in the build is dropped rather than rendered as a hole, so the list above can outlive a brand this fork has not picked up yet. */
const resolve = (ids: string[]): IconEntry[] =>
  ids
    .map((id) => byId.get(id))
    .filter((entry): entry is IconEntry => Boolean(entry) && Boolean(ICONS[entry!.id]));

export const featured: IconEntry[] = resolve(ORDER);

export const featuredServices: IconEntry[] = resolve(SERVICE_ORDER);

export const featuredIcon = (id: string): CompoundIcon | undefined => ICONS[id];

export const featuredMark = (entry: IconEntry) => preferred(ICONS[entry.id], entry);

/**
 * Deals the featured brands into `count` marquee tracks round-robin, so each row mixes colour marks with monochrome ones instead of one row getting all the colour.
 */
export const marqueeRows = (count: number, perRow: number): IconEntry[][] => {
  const rows: IconEntry[][] = Array.from({ length: count }, () => []);
  featured.forEach((entry, index) => {
    const row = rows[index % count];
    if (row.length < perRow) row.push(entry);
  });
  return rows;
};
